create database customer_behavior;

use customer_behavior;

select * from customer;

-- 1. What is the total revenue generated by male vs female customers?

select gender, sum(purchase_amount) from customer group by gender;

-- 2. which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount from customer where discount_applied = 'yes' and 
purchase_amount > (select avg(purchase_amount) from customer);

-- 3. which are the top 5 products with highest avg review rating?

select item_purchased, round(avg(review_rating), 2) as avg_rating from customer group by item_purchased order by avg(review_rating) desc limit 5;

select distinct r.item_purchased, r.avg_rating from 
(select item_purchased, avg(review_rating) over(partition by item_purchased) as avg_rating from customer) as r
order by avg_rating desc limit 5;

-- 4. compare the avg purchase amounts between standard and express shipping.

select Shipping_type, avg(purchase_amount) from customer where shipping_type in ('express', 'standard') group by shipping_type;

-- 5. do subscribed customers spend more? compare avg spend and total revenue between subscribers and non-subscribers

select subscription_status, count(customer_id) as no_customers, round(avg(purchase_amount),2) as avg_spend , sum(purchase_amount) as total_revenue from customer group by subscription_status;

-- 6. which 5 products have the highest percentage of purchases with discount applied?
 
 select item_purchased,
 round((sum(case when discount_applied = 'yes' then 1 else 0 end) / count(*)) * 100, 2) as percentage
 from customer
 group by item_purchased
 order by percentage desc
 limit 5;

-- 7. Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from customer)

select customer_segment, count(*) as 'number of customer'
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category

with item_counts as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rnk
from customer
group by category, item_purchased)

select item_rnk, category, item_purchased, total_orders
from item_counts
where item_rnk <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from  customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group?

select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;

